### ISSUE TITLE
Encoding for custom table per column

### ISSUE THREAD

**Issue by Rucchao** [hyrise/encoding_selection#2]
Hi Martin,

 I am wondering how could I encode the custom data when loading the data into hyrise. If I have a tbl table with two columns, how could I load it with a specified json configuration per column? 

Any instructions are appreciated. Thanks!

Best,
Chao

**Comment by Bouncner** [comment]
Hey Chao,

sorry for the late response. Apparently I am not notified automatically. Sorry.

There are different ways, depending on what you want to achieve/what works best for you.

You could use Hyrise's benchmark binary called `hyriseBenchmarkFileBased`. You can pass a path to TBL files, a path to queries, and a JSON encoding file. I haven't worked with it for quite a while though.

For more flexibility, I personally always preferred to use Python and work with the Hyrise server via the postgres protocol. See the `python/runner.py`. This file loads table files (in this case for the Join Order Benchmark, see `load_table`) and instructs Hyrise to apply a compression configuration (`'APPLY COMPRESSION CONFIGURATION ...`).

For the second approach, you need to use the branch used in this project here, as this has not made into Hyrise's master branch. We now support something like custom commands in Hyrise via plugins, but that has been integrated just recently and was not part of the paper project.

**Comment by Rucchao** [comment]
No worry. Thanks for your response! It seems the second approach is appealing, I'll try it out. Thanks!

Chao

**Comment by Bouncner** [comment]
Closing now. Feel free to reopen any time in case you have questions.
